spring:
  application:
    name: spring-webflux-sample
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  # TODO: logbackの方に書き込む
  pattern:
    level:  "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    web: DEBUG